# CI For Product Catalog Microservice
name: product-catalog-ci
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Setup Go Language V1.22
              uses: actions/setup-go@v2
              with:
                go-version: 1.22
            
            - name: Build Code
              run: |
                cd src/product-catalog
                go mod download
                go build -o product-catalog-service main.go

            - name: Run Unit Tests
              run: |
                cd src/product-catalog
                go test ./...

    code-quality:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Setup Go Language V1.22
              uses: actions/setup-go@v2
              with:
                go-version: 1.22

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: v1.55.2
                run: golangci-lint run
                working-directory: src/product-catalog
    
    docker-build:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install Docker
              uses: docker/setup-buildx-action@v1

            - name: Login Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Push
              uses: docker/build-push-action@v6
              with:
                context: src/product-catalog
                file: src/product-catalog/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{github.run_id}}

    updatek8s:
        runs-on: ubuntu-latest
        needs: docker-build
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GIT_ACCESS_TOKEN }}
            
            - name: Update Kubernetes Deployment Manifest
              run: |
                sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{github.run_id}}|" kubernetes/productcatalog/deploy.yaml

            - name: Commit and Push Changes
              run: |
                git config --global user.email "bhargavharshith7@gmail.com"
                git config --global user.name "Bhargav Harshith"
                git add kubernetes/productcatalog/deploy.yaml
                git commit -m "[CI]: Update Deployment Manifest File with New Image Tag ${{github.run_id}}"
                git push origin HEAD:main -f

